describe("bunsetsu.lang (Japanese/English detection)", function()
  local lang = require("bunsetsu._core.lang")

  describe("has_japanese()", function()
    it("detects kana and kanji", function()
      assert.is_true(lang.has_japanese("これはテスト"))
      assert.is_true(lang.has_japanese("漢字"))
    end)

    it("rejects ascii and empty text", function()
      assert.is_false(lang.has_japanese("hello world"))
      assert.is_false(lang.has_japanese(""))
      assert.is_false(lang.has_japanese("123!?"))
    end)

    it("detects japanese in mixed text", function()
      assert.is_true(lang.has_japanese("Vimはエディタです"))
    end)
  end)

  describe("jp_count() / ascii_letter_count()", function()
    it("counts kana and kanji characters", function()
      assert.are.equal(3, lang.jp_count("これは"))
      assert.are.equal(3, lang.jp_count("漢字だ"))
      assert.are.equal(0, lang.jp_count("hello"))
    end)

    it("counts ascii letters", function()
      assert.are.equal(5, lang.ascii_letter_count("Vim は UI"))
      assert.are.equal(0, lang.ascii_letter_count("かな"))
    end)
  end)

  describe("script()", function()
    it("classifies japanese text, including mixed text", function()
      assert.are.equal("japanese", lang.script("これはテスト"))
      assert.are.equal("japanese", lang.script("Vimはエディタ"))
    end)

    it("classifies english text", function()
      assert.are.equal("english", lang.script("hello world"))
      assert.are.equal("english", lang.script("It's 3:00 pm."))
    end)

    it("classifies digits/symbols-only text as other", function()
      assert.are.equal("other", lang.script("123"))
      assert.are.equal("other", lang.script(""))
      assert.are.equal("other", lang.script("..."))
    end)
  end)
end)
